### ISSUE TITLE
can't write to last row of terminal

### ISSUE THREAD

**Issue by stephentalley** [varabyte/kotter#103]
A simple attempt at putting "line \<i\>" in every row of the terminal:

    session {
        section {
            for (i in 0..<height) {
                textLine("line $i")
            }
        }.runUntilKeyPressed(Keys.Q, Keys.ESC) {
        }
    }

…unexpectedly results in the terminal contents being scrolled up one line, leaving the last line blank:

![screenshot-2023 12 17 14 20 39](https://github.com/varabyte/kotter/assets/3507182/59e35d1d-8a05-4e57-accf-412fe081de8e)

I thought maybe the newline in the last line was causing this, so I changed the code to:

    session {
        section {
            for (i in 0..<height) {
                if (i == height - 1) {
                    text("line $i")
                } else {
                    textLine("line $i")
                }
            }
        }.runUntilKeyPressed(Keys.Q, Keys.ESC) {
        }
    }

…but the issue remains.

What I expect/am hoping for:

![screenshot-2023 12 17 14 37 12](https://github.com/varabyte/kotter/assets/3507182/be8ec35f-6159-45c0-85d7-571ee429e7f2)

Apologies if I'm just misunderstanding the API, but I was unable to find any documentation or code that addressed this.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.1.1

**Comment by bitspittle** [comment]
*Really sorry for not responding to this earlier! I never saw any notification....*

Yeah this is working as intended. The idea is that a section is an isolated block of text.

Otherwise this would cause big problems due to how terminal repainting works:

```kotlin
 section { text("bad ") }.run()
 section { text("case ") }.run()
 section { text("example ") }.run()
 var count by liveVarOf(0)
 section {
    text("Count #${count + 1}")
 }.runUntilKeyPressed(ESC) {
    onTimer(100.ms) { ++count }
 }
```
How could I know where to start repainting from? The terminal APIs are very simple and very limited. All I can do consistently is wipe the whole line.

I hope this helps explain the reasoning behind the API design here.

**Comment by 239** [comment]
~~I think this should be reopened~~ moved to #132

**Comment by bitspittle** [comment]
The design for sections to end in a newline is VERY intentional. Otherwise all our line width calculations would be unreliable after the first section. It's the same reason we clear all visual state (colors, text effects) at the end of a section.

You should think of a section as a very district part of your CLI application, that once finished you move on, freeze its text, and mentally discard it. If you need something where the last section flows into the next, that should really just be a single section and not two.

Unfortunately that means we need to keep an extra blank line for after the section. But maybe it's possible to ignore that requirement untill AFTER a section is finished running, I'll think about it.

**Comment by 239** [comment]
I appreciate your patient explanation, I see the point better now. What do you think about these rash ideas?
1. explicit flag for preventing newline:
```Kotlin
    section(newline = false) { text("...") }
    section { textLine(); textLine("this section is responsible") }
```
2. moving the newline check from end to start: if there is a way to check if a section begins on an empty line or not, then insert newline as the first command. Then trailing empty lines could be removed.

**Comment by bitspittle** [comment]
I'm going to try not adding the newline until the run section is finished..I think that will be clean if it works and it will get you what you want

**Comment by 239** [comment]
I am in favor of a clean solution with minimal changes, it would be great if that worked out.
Although I am aware that Kotter is not designed primarily for this purpose, but my application started with a simple CLI which now looks more like a TUI. It works better than expected and I am quite satisfied with the result so far.
While the newline at the bottom is not an issue for most console applications, the unused space is a little annoying for "full screen" sections, especially in smaller windows.

**Comment by 239** [comment]
moved to #131

**Comment by bitspittle** [comment]
Honestly it could be great if you file two new issues, one for not adding the newline on an active section, and another for this new concern about width + 1
